name: 'TypeSchema Code Generator'
description: 'This action can automatically generate code based on a TypeSchema specification'
author: 'Apioo'
branding:
  icon: archive
  color: blue
inputs:
  format:
    description: 'The target language, possible values are: csharp, go, java, php, python, ruby, rust, typescript or visualbasic'
    required: true
  namespace:
    description: 'Optional a namespace for the generated code'
    required: false
  source:
    description: 'Location of the TypeSchema source, this can be either a local file at your repository or a remote source like an `https://` url or a TypeHub source i.e. `typehub://apioo:developer@1.0.1`'
    required: true
    default: './typeschema.json'
  output:
    description: 'The output directory where the generated files are placed. NOTE the action will delete all files from this directory before code generation to have a clean state and to remove files which are no longer needed'
    required: true
  token:
    description: 'Github access token to be able to commit the files to your repository'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'The target repository'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.output }}
    - ${{ inputs.format }}
    - ${{ inputs.namespace }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
